[workspace]

members = [
    "packages/launcher/src-tauri",
    "packages/server",
    "packages/cli",
]

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"
lto = true
codegen-units = 1
